### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by innerop** [belladoreai/llama-tokenizer-js#3]
Hi

Cool stuff and thanks for sharing! 

I can get the tokens in an array and get the length of that array to find out the number of tokens. 

But how do I know which token corresponds to which characters so I can color them the way you do in the demo? Just wondering if that's a secret functionality that is not part of this open source package...

Thanks,

**Comment by belladoreai** [comment]
Hi, I'm glad to hear you like the project!

Let's say you want to take individual token 514 and map it to characters. For this you can call `llamaTokenizer.vocabById[514]`, which would return "ell". Note that some individual tokens don't have a good representation as characters.

The demo site with the coloring is not secret functionality. You can find it here: https://github.com/belladoreai/llama-tokenizer-js/blob/master/example-demo/src/App.js#L5-L55

**Comment by innerop** [comment]
Sorry, I should have read the whole set of functions. I had only glanced at the Readme. Maybe it would make things more clear to document the full set of functionality.

How would one go about adapting it to different models? Do you mind sharing your thoughts on the process? Easier I think to document that than to try and satisfy user requests for various models. For example, I might be interested in Falcon rather than OpenLlama, but others may have other models in mind.

**Comment by belladoreai** [comment]
> Maybe it would make things more clear to document the full set of functionality.

Hmmh, okay. I will add this to README:

_Decode only selected individual tokens, without including special beginning-of-prompt tokens:_

```
llamaTokenizer.decode([3186], false, false)
> 'Hello'
```

I suggested using `vocabById` for this purpose to you in my earlier message, but the same thing can be done with the `decode` function with these extra parameters, so I prefer to put that into README.

**Comment by belladoreai** [comment]
> How would one go about adapting it to different models? Do you mind sharing your thoughts on the process? Easier I think to document that than to try and satisfy user requests for various models. For example, I might be interested in Falcon rather than OpenLlama, but others may have other models in mind.

I haven't looked into Falcon, so I don't know what kind of tokenizer it uses.

As for OpenLLaMA, that should be trivial to support by simply changing the vocab and merge data.

As for OpenAI tokenizers, there are multiple other repos which already support those, so it doesn't make sense to put work in to support those here.

I guess there isn't any universal answer, I'll have to look at it on a case by case basis if people ask support for a specific tokenizer.

**Comment by belladoreai** [comment]
I'll close this for now, but feel free to open another issue if you have any more questions.
