### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by innerop** [belladoreai/llama-tokenizer-js#6]
Hi there, 

There are new models coming out everyday that I'd like to test and this tool is quite useful in making sure the instruction and response remain within the model's context window.

However, in order not to repeat your work and instead extend it and contribute back any changes/additions, the following part of the code needs to be explained:

 * 1. base64-encoded vocabulary
 * 2. base64-encoded merge binary

How do you compose the base64 vocab and merge binary?  It's the only opaque part in this project. Everything else looks good and easy to work with.

If you document that part, I can generate those base64 strings for whatever model I happen to be working with and create a pull request for each. You'd have to add a way to select model via some config, e.g. config.modelName 

Thanks

**Comment by belladoreai** [comment]
Hi!

I have now documented in README the process of transforming the vocabulary and merge data into the format that is used.

Note that the new models which are coming out every day are almost always built on top of the "old LLaMA model", and as such, they use the same tokenizer. So this tokenizer should already be compatible with almost all of the new LLaMA models that are coming out, without needing to modify the vocabulary and merge data.

**Comment by innerop** [comment]
Awesome, for things like Falcon, and the upcoming llama2, but yes I realized yesterday that everybody is just re-training or fine-tuning llama and OpenLlama.
